

CREATE TABLE IF NOT EXISTS empresas
(
id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
nombre VARCHAR NOT NULL UNIQUE,
latitud NUMERIC(9,6)
longitud NUMERIC(9,6),
estado BOOLEAN DEFAULT true NOT NULL
);





CREATE TABLE IF NOT EXISTS cargos(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    empresaid integer references empresas(id),
    nombre VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS periodoslaborales(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cargoid integer references cargo(id) NOT NULL,
    diaid integer references dias(id) NOT NULL,
    horainicio TIME NOT NULL,
    horafin TIME NOT NULL
);



CREATE TABLE IF NOT EXISTS dias(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(10)
);

INSERT INTO dias(nombre) VALUES('Lunes');
INSERT INTO dias(nombre) VALUES('Martes');
INSERT INTO dias(nombre) VALUES('Miercoles');
INSERT INTO dias(nombre) VALUES('Jueves');
INSERT INTO dias(nombre) VALUES('Viernes');
INSERT INTO dias(nombre) VALUES('Sabado');
INSERT INTO dias(nombre) VALUES('Domingo');


CREATE TABLE IF NOT EXISTS empleado
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	id_empresa integer references empresa(id),
    id_cargo integer references cargo(id)
    nombres VARCHAR(80) NOT NULL CHECK(nombres <> ''),
    apellidos VARCHAR(80) NOT NULL CHECK(apellidos <> ''),
    ci VARCHAR(10),
    email VARCHAR(80) NOT NULL UNIQUE,
    password text NOT NULL
);

INSERT INTO EMPLEADO(id_empresa, nombres, apellidos, ci, email, password) VALUES (1, 1, 'William', 'Borja', '1101234567', 'willyborja@gmail.com','A1Q29920A9X0AS9D9ASDAS0asda12');
INSERT INTO EMPLEADO(id_empresa, nombres, apellidos, ci, email, password) VALUES (1, 2,'Bruno', 'Esparza', '1101234567', 'baezparsa@gmail.com','A1Q29920A9X0AS9D9ASDAS0as2da12');
SELECT * FROM EMPLEADO WHERE ID_EMPRESA = 1;





